import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { getDemoStore } from '@/lib/demo-store';
import {
  getDemoDashboardStats,
  getDemoStatusData,
  getDemoWorkloadData,
  getDemoTrendData,
} from '@/lib/demo-analytics';
import { CompletionTrendChart } from '@/components/dashboard/completion-trend-chart';
import { TaskStatusChart } from '@/components/dashboard/task-status-chart';
import { WorkloadChart } from '@/components/dashboard/workload-chart';
import { Brain, AlertTriangle, Info, ShieldAlert } from 'lucide-react';

const severityStyles: Record<string, { label: string; className: string; icon: typeof AlertTriangle }> = {
  critical: { label: 'Critical', className: 'bg-red-50 text-red-700 border-red-200', icon: ShieldAlert },
  warning: { label: 'Warning', className: 'bg-amber-50 text-amber-700 border-amber-200', icon: AlertTriangle },
  info: { label: 'Info', className: 'bg-blue-50 text-blue-700 border-blue-200', icon: Info },
};

export default function AnalyticsPage() {
  const store = getDemoStore();
  const stats = getDemoDashboardStats();
  const statusData = getDemoStatusData();
  const workloadData = getDemoWorkloadData();
  const trendData = getDemoTrendData();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">AI Workforce Analytics</h1>
          <p className="text-sm text-gray-500 mt-1">
            Insights generated by rule-based statistical analysis | Human review required before any action
          </p>
        </div>
        <Badge variant="outline" className="bg-purple-50 text-purple-700 border-purple-200">
          <Brain className="w-3 h-3 mr-1" />
          Rule-Based Analytics
        </Badge>
      </div>

      {/* AI Insights — real output of the analytics engine over the demo store */}
      <Card className="p-6">
        <h2 className="text-lg font-semibold mb-1">AI Insights</h2>
        <p className="text-xs text-gray-500 mb-4">
          Detected by threshold-based statistical detectors (workload CV, delay patterns, utilization).
        </p>
        {store.insights.length === 0 ? (
          <div className="p-4 bg-gray-50 rounded-lg border text-sm text-gray-600">
            No workforce issues detected in the current data — the rule-based detectors only fire when
            workload imbalance, delays, or staffing gaps are found.
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {store.insights.map((insight) => {
              const style = severityStyles[insight.severity] || severityStyles.info;
              const Icon = style.icon;
              return (
                <div key={insight.id} className="p-4 bg-gray-50 rounded-lg border space-y-2">
                  <div className="flex items-center gap-2">
                    <Icon className="w-4 h-4 text-gray-500" />
                    <p className="font-medium flex-1">{insight.title}</p>
                    <Badge variant="outline" className={style.className}>
                      {style.label}
                    </Badge>
                  </div>
                  <p className="text-sm text-gray-600">{insight.description}</p>
                  <p className="text-xs text-gray-400">
                    Data factors: {Object.entries(insight.data_factors || {})
                      .map(([k, v]) => `${k}: ${typeof v === 'number' ? Number(v.toFixed(2)) : v}`)
                      .join(' · ')}
                    {insight.affected_employees?.length ? ` · ${insight.affected_employees.length} employee(s) affected` : ''}
                  </p>
                </div>
              );
            })}
          </div>
        )}
      </Card>

      {/* Workforce snapshot computed from live store data */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: 'Open Tasks', value: stats.pendingTasks + stats.inProgressTasks + stats.acceptedTasks },
          { label: 'Completed / Verified', value: stats.completedTasks },
          { label: 'Delayed', value: stats.delayedTasks },
          { label: 'Active AI Insights', value: store.insights.length },
        ].map((s) => (
          <Card key={s.label} className="p-4 text-center">
            <p className="text-2xl font-bold text-gray-900">{s.value}</p>
            <p className="text-xs text-gray-500">{s.label}</p>
          </Card>
        ))}
      </div>

      {/* Charts — computed from real store data */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <TaskStatusChart data={statusData} />
        <WorkloadChart data={workloadData} />
      </div>

      <CompletionTrendChart data={trendData} />
    </div>
  );
}
